/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package spc;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JComboBox;

/**
 *
 * @author Zarkov
 */
public class CasablancaGUI extends javax.swing.JFrame implements ActionListener
{
    OverviewCells ovc = new OverviewCells();
    private int Room1 = 1;
    private int Room2 = 2;
    private int Room3 = 3;
    private int Room4 = 4;
    private int Room5 = 5;
    private int Room6 = 6;
    private int Room7 = 7;
    private int Room8 = 8;
    private Calendar Day01 = Calendar.getInstance();
    JDBCInsertQuery jdcbinsert = new JDBCInsertQuery();
    JDBCSelectQuery jdcbselect = new JDBCSelectQuery();
    Calendar cal = new GregorianCalendar();
    private int currentYear = Calendar.YEAR;
    Integer[] list28days = new Integer[] {1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28};
    Integer[] list29days = new Integer[] {1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29};
    Integer[] list30days = new Integer[] {1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30};
    Integer[] list31days = new Integer[] {1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31};
    
    /**
     * Creates new form CasablancaGUI
     */
    public CasablancaGUI()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jDialogSearchCustomer = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        jLabelSearchCustomerNoChange1 = new javax.swing.JLabel();
        jTextFieldSearchCustomerFirstName = new javax.swing.JTextField();
        jLabelSearchCustomerNoChange2 = new javax.swing.JLabel();
        jTextFieldSearchCustomerLastName = new javax.swing.JTextField();
        jLabelSearchCustomerNoChange6 = new javax.swing.JLabel();
        jTextFieldSearchCustomerGuestID = new javax.swing.JTextField();
        jLabelSearchCustomerNoChange7 = new javax.swing.JLabel();
        jTextFieldSearchCustomerBookingID = new javax.swing.JTextField();
        jButtonSearchCustomerDetails = new javax.swing.JButton();
        jLabelSearchCustomerNoChange3 = new javax.swing.JLabel();
        jTextFieldSearchCustomerCountry = new javax.swing.JTextField();
        jLabelSearchCustomerNoChange4 = new javax.swing.JLabel();
        jTextFieldSearchCustomerPhoneNumber = new javax.swing.JTextField();
        jTextFieldSearchCustomerEmail = new javax.swing.JTextField();
        jLabelSearchCustomerNoChange5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabelSearchCustomerFirstName = new javax.swing.JLabel();
        jLabelSearchCustomerLastName = new javax.swing.JLabel();
        jButtonShowSelectedCustomerDetails = new javax.swing.JButton();
        jLabelSearchCustomerNationality = new javax.swing.JLabel();
        jLabelSearchCustomerPhone = new javax.swing.JLabel();
        jLabelSearchCustomerEmail = new javax.swing.JLabel();
        jLabelSearchCustomerNoChange8 = new javax.swing.JLabel();
        jLabelSearchCustomerNoChange9 = new javax.swing.JLabel();
        jLabelSearchCustomerNoChange10 = new javax.swing.JLabel();
        jLabelSearchCustomerNoChange11 = new javax.swing.JLabel();
        jLabelSearchCustomerNoChange12 = new javax.swing.JLabel();
        jLabelSearchCustomerNoChange13 = new javax.swing.JLabel();
        jLabelSearchCustomerGuestID = new javax.swing.JLabel();
        jLabelSearchCustomerBookingID = new javax.swing.JLabel();
        jLabelSearchCustomerNoChange14 = new javax.swing.JLabel();
        jButtonEditSelectedCustomerDetails = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListSearchCustomerResult = new javax.swing.JList();
        jDialogSearchRoom = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jRadioButtonSearchRoomAvailable = new javax.swing.JRadioButton();
        jRadioButtonSearchRoomCheckInOut = new javax.swing.JRadioButton();
        jRadioButtonSearchRoomOccupied = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabelSearchRoomNoChange1 = new javax.swing.JLabel();
        jComboBoxSearchRoomType = new javax.swing.JComboBox();
        jLabelSearchRoomTypePersonsNotifier = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jPanel3 = new javax.swing.JPanel();
        jLabelSearchNoChange2 = new javax.swing.JLabel();
        jComboBoxSearchStartMonth = new javax.swing.JComboBox();
        jComboBoxSearchStartDate = new javax.swing.JComboBox();
        jComboBoxSearchStartYear = new javax.swing.JComboBox();
        jLabelSearchNoChange4 = new javax.swing.JLabel();
        jComboBoxSearchEndMonth = new javax.swing.JComboBox();
        jComboBoxSearchEndDate = new javax.swing.JComboBox();
        jComboBoxSearchEndYear = new javax.swing.JComboBox();
        jButtonRoomSearch = new javax.swing.JButton();
        jLabelSearchRoomResultNotifier = new javax.swing.JLabel();
        buttonGroupSearchRoomChoice = new javax.swing.ButtonGroup();
        jDialogBooking = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabelBookingNoChange1 = new javax.swing.JLabel();
        jTextFieldBookingFirstName = new javax.swing.JTextField();
        jLabelBookingNoChange2 = new javax.swing.JLabel();
        jTextFieldBookingLastName = new javax.swing.JTextField();
        jLabelBookingNoChange3 = new javax.swing.JLabel();
        jTextFieldBookingCountry = new javax.swing.JTextField();
        jLabelBookingNoChange4 = new javax.swing.JLabel();
        jTextFieldBookingPhoneNumber = new javax.swing.JTextField();
        jLabelBookingNoChange5 = new javax.swing.JLabel();
        jTextFieldBookingEmail = new javax.swing.JTextField();
        jLabelBookingNoChange6 = new javax.swing.JLabel();
        jTextFieldBookingGuestID = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabelBookingNoChange8 = new javax.swing.JLabel();
        jComboBoxBookingStartMonth = new javax.swing.JComboBox();
        jComboBoxBookingStartDate = new javax.swing.JComboBox();
        jComboBoxBookingStartYear = new javax.swing.JComboBox();
        jLabelBookingNoChange9 = new javax.swing.JLabel();
        jComboBoxBookingEndMonth = new javax.swing.JComboBox();
        jComboBoxBookingEndDate = new javax.swing.JComboBox();
        jComboBoxBookingEndYear = new javax.swing.JComboBox();
        jButtonBookingBook = new javax.swing.JButton();
        jTextFieldBookingRoomNumber = new javax.swing.JTextField();
        jLabelBookingNoChange10 = new javax.swing.JLabel();
        jLabelBookingUnavailableNotifier = new javax.swing.JLabel();
        jPanelOverview = new javax.swing.JPanel();
        jButtonBooking = new javax.swing.JButton();
        jButtonSearchCustomer = new javax.swing.JButton();
        jButtonEditBooking = new javax.swing.JButton();
        jButtonSearchRoom = new javax.swing.JButton();
        jButtonRoomArrowUp = new javax.swing.JButton();
        jButtonRoomArrowDown = new javax.swing.JButton();
        jButtonPrevious14Days = new javax.swing.JButton();
        jButtonPrevious7Days = new javax.swing.JButton();
        jButtonNext14Days = new javax.swing.JButton();
        jButtonNext7Days = new javax.swing.JButton();
        jButtonFacilities = new javax.swing.JButton();
        jButtonSetupOverview = new javax.swing.JButton();
        jButtonResetOveriew = new javax.swing.JButton();
        overviewCells1 = new spc.OverviewCells();

        jDialogSearchCustomer.setTitle("Search Customer Details");
        jDialogSearchCustomer.setMinimumSize(new java.awt.Dimension(733, 509));
        jDialogSearchCustomer.setResizable(false);

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.setPreferredSize(new java.awt.Dimension(300, 270));

        jLabelSearchCustomerNoChange1.setText("First Name:");

        jTextFieldSearchCustomerFirstName.setPreferredSize(new java.awt.Dimension(192, 20));

        jLabelSearchCustomerNoChange2.setText("Last Name:");

        jTextFieldSearchCustomerLastName.setPreferredSize(new java.awt.Dimension(192, 20));

        jLabelSearchCustomerNoChange6.setText("Guest-ID");

        jTextFieldSearchCustomerGuestID.setPreferredSize(new java.awt.Dimension(192, 20));

        jLabelSearchCustomerNoChange7.setText("Booking-ID");

        jTextFieldSearchCustomerBookingID.setPreferredSize(new java.awt.Dimension(192, 20));

        jButtonSearchCustomerDetails.setText("Search for customer details");
        jButtonSearchCustomerDetails.setPreferredSize(new java.awt.Dimension(192, 20));
        jButtonSearchCustomerDetails.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonSearchCustomerDetailsActionPerformed(evt);
            }
        });

        jLabelSearchCustomerNoChange3.setText("Country:");

        jTextFieldSearchCustomerCountry.setPreferredSize(new java.awt.Dimension(192, 20));

        jLabelSearchCustomerNoChange4.setText("Phone Number:");

        jTextFieldSearchCustomerPhoneNumber.setPreferredSize(new java.awt.Dimension(192, 20));

        jTextFieldSearchCustomerEmail.setPreferredSize(new java.awt.Dimension(192, 20));

        jLabelSearchCustomerNoChange5.setText("E-mail Address:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel1.setText("<html>Type in one or more information in the<br>boxes below:</html>");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelSearchCustomerNoChange7)
                            .addComponent(jLabelSearchCustomerNoChange6)
                            .addComponent(jLabelSearchCustomerNoChange2)
                            .addComponent(jLabelSearchCustomerNoChange1)
                            .addComponent(jTextFieldSearchCustomerLastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldSearchCustomerGuestID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldSearchCustomerBookingID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSearchCustomerDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldSearchCustomerFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSearchCustomerNoChange3)
                            .addComponent(jTextFieldSearchCustomerCountry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSearchCustomerNoChange4)
                            .addComponent(jTextFieldSearchCustomerPhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldSearchCustomerEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSearchCustomerNoChange5))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1))
                .addGap(10, 10, 10))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabelSearchCustomerNoChange1)
                .addGap(0, 0, 0)
                .addComponent(jTextFieldSearchCustomerFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabelSearchCustomerNoChange2)
                .addGap(0, 0, 0)
                .addComponent(jTextFieldSearchCustomerLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabelSearchCustomerNoChange3)
                .addGap(0, 0, 0)
                .addComponent(jTextFieldSearchCustomerCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabelSearchCustomerNoChange4)
                .addGap(0, 0, 0)
                .addComponent(jTextFieldSearchCustomerPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabelSearchCustomerNoChange5)
                .addGap(0, 0, 0)
                .addComponent(jTextFieldSearchCustomerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabelSearchCustomerNoChange6)
                .addGap(0, 0, 0)
                .addComponent(jTextFieldSearchCustomerGuestID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabelSearchCustomerNoChange7)
                .addGap(0, 0, 0)
                .addComponent(jTextFieldSearchCustomerBookingID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jButtonSearchCustomerDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelSearchCustomerFirstName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelSearchCustomerFirstName.setPreferredSize(new java.awt.Dimension(230, 20));

        jLabelSearchCustomerLastName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelSearchCustomerLastName.setPreferredSize(new java.awt.Dimension(230, 20));

        jButtonShowSelectedCustomerDetails.setText("Show details for selected customer");
        jButtonShowSelectedCustomerDetails.setPreferredSize(new java.awt.Dimension(163, 25));

        jLabelSearchCustomerNationality.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelSearchCustomerNationality.setPreferredSize(new java.awt.Dimension(230, 20));

        jLabelSearchCustomerPhone.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelSearchCustomerPhone.setPreferredSize(new java.awt.Dimension(230, 20));

        jLabelSearchCustomerEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelSearchCustomerEmail.setPreferredSize(new java.awt.Dimension(230, 20));

        jLabelSearchCustomerNoChange8.setText("First Name:");

        jLabelSearchCustomerNoChange9.setText("Last Name:");

        jLabelSearchCustomerNoChange10.setText("Country:");

        jLabelSearchCustomerNoChange11.setText("Phone Number:");

        jLabelSearchCustomerNoChange12.setText("E-mail Address:");

        jLabelSearchCustomerNoChange13.setText("Guest-ID");

        jLabelSearchCustomerGuestID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelSearchCustomerGuestID.setPreferredSize(new java.awt.Dimension(230, 20));

        jLabelSearchCustomerBookingID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelSearchCustomerBookingID.setPreferredSize(new java.awt.Dimension(230, 20));

        jLabelSearchCustomerNoChange14.setText("Booking-ID");

        jButtonEditSelectedCustomerDetails.setText("Edit selected customer");
        jButtonEditSelectedCustomerDetails.setPreferredSize(new java.awt.Dimension(75, 25));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelSearchCustomerNoChange8)
                    .addComponent(jLabelSearchCustomerNoChange9)
                    .addComponent(jLabelSearchCustomerLastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSearchCustomerNoChange10)
                    .addComponent(jLabelSearchCustomerNationality, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSearchCustomerNoChange11)
                    .addComponent(jLabelSearchCustomerPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSearchCustomerNoChange12)
                    .addComponent(jLabelSearchCustomerEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSearchCustomerFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSearchCustomerNoChange13)
                    .addComponent(jLabelSearchCustomerGuestID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSearchCustomerBookingID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSearchCustomerNoChange14)
                    .addComponent(jButtonShowSelectedCustomerDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonEditSelectedCustomerDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jButtonShowSelectedCustomerDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabelSearchCustomerNoChange8)
                .addGap(0, 0, 0)
                .addComponent(jLabelSearchCustomerFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabelSearchCustomerNoChange9)
                .addGap(0, 0, 0)
                .addComponent(jLabelSearchCustomerLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabelSearchCustomerNoChange10)
                .addGap(0, 0, 0)
                .addComponent(jLabelSearchCustomerNationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabelSearchCustomerNoChange11)
                .addGap(0, 0, 0)
                .addComponent(jLabelSearchCustomerPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabelSearchCustomerNoChange12)
                .addGap(0, 0, 0)
                .addComponent(jLabelSearchCustomerEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabelSearchCustomerNoChange13)
                .addGap(0, 0, 0)
                .addComponent(jLabelSearchCustomerGuestID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabelSearchCustomerNoChange14)
                .addGap(0, 0, 0)
                .addComponent(jLabelSearchCustomerBookingID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonEditSelectedCustomerDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jListSearchCustomerResult.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jListSearchCustomerResult);

        javax.swing.GroupLayout jDialogSearchCustomerLayout = new javax.swing.GroupLayout(jDialogSearchCustomer.getContentPane());
        jDialogSearchCustomer.getContentPane().setLayout(jDialogSearchCustomerLayout);
        jDialogSearchCustomerLayout.setHorizontalGroup(
            jDialogSearchCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogSearchCustomerLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jDialogSearchCustomerLayout.setVerticalGroup(
            jDialogSearchCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jDialogSearchCustomerLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1)
                .addGap(10, 10, 10))
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );

        jDialogSearchRoom.setTitle("Search Room Details");
        jDialogSearchRoom.setMinimumSize(new java.awt.Dimension(573, 539));
        jDialogSearchRoom.setResizable(false);

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jRadioButtonSearchRoomAvailable.setSelected(true);
        jRadioButtonSearchRoomAvailable.setText("Search for rooms available in the entire specified period.");

        jRadioButtonSearchRoomCheckInOut.setText("<html>Search for rooms with check-in/check-out<br>on the specified start date.</html>");

        jRadioButtonSearchRoomOccupied.setText("Search for rooms occupied in the entire specified period.");

        jRadioButton1.setText("<html>Search for rooms with the selected amount of<br>consecutive days available in the specified period.</html>");

        jLabelSearchRoomNoChange1.setText("Search among room type:");
        jLabelSearchRoomNoChange1.setPreferredSize(new java.awt.Dimension(124, 22));

        jComboBoxSearchRoomType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All rooms", "Single room", "Double room", "Family room" }));
        jComboBoxSearchRoomType.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jComboBoxSearchRoomTypeActionPerformed(evt);
            }
        });

        jLabelSearchRoomTypePersonsNotifier.setText("(5 persons)");
        jLabelSearchRoomTypePersonsNotifier.setPreferredSize(new java.awt.Dimension(70, 22));

        jComboBox1.setMaximumRowCount(14);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1 day", "2 days", "3 days", "4 days", "5 days", "6 days", "7 days", "8 days", "9 days", "10 days", "11 days", "12 days", "13 days", "14 days", "15 days", "16 days", "17 days", "18 days", "19 days", "20 days", "21 days", "22 days", "23 days", "24 days", "25 days", "26 days", "27 days", "28 days" }));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonSearchRoomAvailable)
                            .addComponent(jRadioButtonSearchRoomCheckInOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonSearchRoomOccupied)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabelSearchRoomNoChange1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jComboBoxSearchRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabelSearchRoomTypePersonsNotifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelSearchRoomNoChange1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelSearchRoomTypePersonsNotifier, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxSearchRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addComponent(jRadioButtonSearchRoomAvailable)
                .addGap(20, 20, 20)
                .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jRadioButtonSearchRoomOccupied)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonSearchRoomCheckInOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jList1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelSearchNoChange2.setText("Specify start date:");

        jComboBoxSearchStartMonth.setMaximumRowCount(13);
        jComboBoxSearchStartMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " - Today -", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        jComboBoxSearchStartDate.setMaximumRowCount(13);
        jComboBoxSearchStartDate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jComboBoxSearchStartYear.setMaximumRowCount(13);
        jComboBoxSearchStartYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040" }));

        jLabelSearchNoChange4.setText("Specify end date:");

        jComboBoxSearchEndMonth.setMaximumRowCount(12);
        jComboBoxSearchEndMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        jComboBoxSearchEndDate.setMaximumRowCount(12);
        jComboBoxSearchEndDate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jComboBoxSearchEndYear.setMaximumRowCount(12);
        jComboBoxSearchEndYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040" }));

        jButtonRoomSearch.setText("Search Rooms");
        jButtonRoomSearch.setPreferredSize(new java.awt.Dimension(270, 25));
        jButtonRoomSearch.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonRoomSearchActionPerformed(evt);
            }
        });

        jLabelSearchRoomResultNotifier.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSearchRoomResultNotifier.setText("28 rooms found...");
        jLabelSearchRoomResultNotifier.setPreferredSize(new java.awt.Dimension(178, 20));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jComboBoxSearchStartMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxSearchStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxSearchStartYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelSearchNoChange2)
                    .addComponent(jLabelSearchNoChange4)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jComboBoxSearchEndMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxSearchEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxSearchEndYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonRoomSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabelSearchRoomResultNotifier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelSearchNoChange2)
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxSearchStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxSearchStartMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxSearchStartYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabelSearchNoChange4)
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxSearchEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxSearchEndMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxSearchEndYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(102, 102, 102)
                .addComponent(jLabelSearchRoomResultNotifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jButtonRoomSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jDialogSearchRoomLayout = new javax.swing.GroupLayout(jDialogSearchRoom.getContentPane());
        jDialogSearchRoom.getContentPane().setLayout(jDialogSearchRoomLayout);
        jDialogSearchRoomLayout.setHorizontalGroup(
            jDialogSearchRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogSearchRoomLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jDialogSearchRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogSearchRoomLayout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jDialogSearchRoomLayout.setVerticalGroup(
            jDialogSearchRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogSearchRoomLayout.createSequentialGroup()
                .addGroup(jDialogSearchRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jDialogBooking.setMinimumSize(new java.awt.Dimension(467, 431));

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelBookingNoChange1.setText("Enter First Name:");

        jTextFieldBookingFirstName.setPreferredSize(new java.awt.Dimension(192, 20));

        jLabelBookingNoChange2.setText("Enter Last Name:");

        jTextFieldBookingLastName.setPreferredSize(new java.awt.Dimension(192, 20));

        jLabelBookingNoChange3.setText("Enter Country:");

        jTextFieldBookingCountry.setPreferredSize(new java.awt.Dimension(192, 20));

        jLabelBookingNoChange4.setText("Enter Phone-Number:");

        jTextFieldBookingPhoneNumber.setPreferredSize(new java.awt.Dimension(192, 20));

        jLabelBookingNoChange5.setText("Enter E-mail Address:");

        jTextFieldBookingEmail.setPreferredSize(new java.awt.Dimension(192, 20));

        jLabelBookingNoChange6.setText("Enter Guest-ID");

        jTextFieldBookingGuestID.setPreferredSize(new java.awt.Dimension(192, 20));

        jButton3.setText("Create ID");
        jButton3.setPreferredSize(new java.awt.Dimension(91, 20));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelBookingNoChange6)
                    .addComponent(jLabelBookingNoChange2)
                    .addComponent(jLabelBookingNoChange1)
                    .addComponent(jTextFieldBookingLastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldBookingFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBookingNoChange3)
                    .addComponent(jTextFieldBookingCountry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBookingNoChange4)
                    .addComponent(jTextFieldBookingPhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldBookingEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBookingNoChange5)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jTextFieldBookingGuestID, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelBookingNoChange1)
                .addGap(0, 0, 0)
                .addComponent(jTextFieldBookingFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabelBookingNoChange2)
                .addGap(0, 0, 0)
                .addComponent(jTextFieldBookingLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabelBookingNoChange3)
                .addGap(0, 0, 0)
                .addComponent(jTextFieldBookingCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabelBookingNoChange4)
                .addGap(0, 0, 0)
                .addComponent(jTextFieldBookingPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabelBookingNoChange5)
                .addGap(0, 0, 0)
                .addComponent(jTextFieldBookingEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabelBookingNoChange6)
                .addGap(0, 0, 0)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBookingGuestID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelBookingNoChange8.setText("Start date:");

        jComboBoxBookingStartMonth.setMaximumRowCount(13);
        jComboBoxBookingStartMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " - Today -", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        jComboBoxBookingStartMonth.setPreferredSize(new java.awt.Dimension(78, 20));
        jComboBoxBookingStartMonth.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jComboBoxBookingStartMonthActionPerformed(evt);
            }
        });

        jComboBoxBookingStartDate.setMaximumRowCount(13);
        jComboBoxBookingStartDate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jComboBoxBookingStartDate.setPreferredSize(new java.awt.Dimension(38, 20));

        jComboBoxBookingStartYear.setMaximumRowCount(13);
        jComboBoxBookingStartYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040" }));
        jComboBoxBookingStartYear.setPreferredSize(new java.awt.Dimension(50, 20));
        jComboBoxBookingStartYear.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jComboBoxBookingStartYearActionPerformed(evt);
            }
        });

        jLabelBookingNoChange9.setText("End date:");

        jComboBoxBookingEndMonth.setMaximumRowCount(12);
        jComboBoxBookingEndMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        jComboBoxBookingEndMonth.setPreferredSize(new java.awt.Dimension(78, 20));
        jComboBoxBookingEndMonth.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jComboBoxBookingEndMonthActionPerformed(evt);
            }
        });

        jComboBoxBookingEndDate.setMaximumRowCount(12);
        jComboBoxBookingEndDate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jComboBoxBookingEndDate.setPreferredSize(new java.awt.Dimension(38, 20));

        jComboBoxBookingEndYear.setMaximumRowCount(12);
        jComboBoxBookingEndYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040" }));
        jComboBoxBookingEndYear.setPreferredSize(new java.awt.Dimension(50, 20));
        jComboBoxBookingEndYear.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jComboBoxBookingEndYearActionPerformed(evt);
            }
        });

        jButtonBookingBook.setText("Book Room");
        jButtonBookingBook.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonBookingBookActionPerformed(evt);
            }
        });

        jTextFieldBookingRoomNumber.setPreferredSize(new java.awt.Dimension(60, 20));

        jLabelBookingNoChange10.setText("Room Number:");

        jLabelBookingUnavailableNotifier.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabelBookingUnavailableNotifier.setText("<html>Selected room is not available<br>in the specified period...</html>");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelBookingUnavailableNotifier)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jComboBoxBookingStartMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxBookingStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxBookingStartYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelBookingNoChange8)
                    .addComponent(jLabelBookingNoChange9)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jComboBoxBookingEndMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxBookingEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxBookingEndYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonBookingBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextFieldBookingRoomNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelBookingNoChange10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelBookingNoChange8)
                .addGap(0, 0, 0)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxBookingStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxBookingStartMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxBookingStartYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabelBookingNoChange9)
                .addGap(0, 0, 0)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxBookingEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxBookingEndMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxBookingEndYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabelBookingNoChange10)
                .addGap(0, 0, 0)
                .addComponent(jTextFieldBookingRoomNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabelBookingUnavailableNotifier, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButtonBookingBook, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialogBookingLayout = new javax.swing.GroupLayout(jDialogBooking.getContentPane());
        jDialogBooking.getContentPane().setLayout(jDialogBookingLayout);
        jDialogBookingLayout.setHorizontalGroup(
            jDialogBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogBookingLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jDialogBookingLayout.setVerticalGroup(
            jDialogBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Overview");
        setMinimumSize(new java.awt.Dimension(967, 662));

        jButtonBooking.setText("New Booking");
        jButtonBooking.setPreferredSize(new java.awt.Dimension(120, 35));
        jButtonBooking.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonBookingActionPerformed(evt);
            }
        });

        jButtonSearchCustomer.setText("Search Customer");
        jButtonSearchCustomer.setPreferredSize(new java.awt.Dimension(120, 35));
        jButtonSearchCustomer.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonSearchCustomerActionPerformed(evt);
            }
        });

        jButtonEditBooking.setText("Edit Booking");
        jButtonEditBooking.setPreferredSize(new java.awt.Dimension(120, 35));
        jButtonEditBooking.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonEditBookingActionPerformed(evt);
            }
        });

        jButtonSearchRoom.setText("Search Room");
        jButtonSearchRoom.setPreferredSize(new java.awt.Dimension(120, 35));
        jButtonSearchRoom.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonSearchRoomActionPerformed(evt);
            }
        });

        jButtonRoomArrowUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/ArrowUp.png"))); // NOI18N
        jButtonRoomArrowUp.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonRoomArrowUp.setPreferredSize(new java.awt.Dimension(41, 26));
        jButtonRoomArrowUp.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonRoomArrowUpActionPerformed(evt);
            }
        });

        jButtonRoomArrowDown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/ArrowDown.png"))); // NOI18N
        jButtonRoomArrowDown.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonRoomArrowDown.setPreferredSize(new java.awt.Dimension(41, 26));
        jButtonRoomArrowDown.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonRoomArrowDownActionPerformed(evt);
            }
        });

        jButtonPrevious14Days.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/ArrowDoubleLeft.png"))); // NOI18N
        jButtonPrevious14Days.setText("Previous 14 days");
        jButtonPrevious14Days.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonPrevious14Days.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonPrevious14Days.setPreferredSize(new java.awt.Dimension(75, 20));

        jButtonPrevious7Days.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/ArrowLeft.png"))); // NOI18N
        jButtonPrevious7Days.setText("Previous 7 days");
        jButtonPrevious7Days.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonPrevious7Days.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonPrevious7Days.setPreferredSize(new java.awt.Dimension(75, 20));

        jButtonNext14Days.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/ArrowDoubleRight.png"))); // NOI18N
        jButtonNext14Days.setText("Next 14 days");
        jButtonNext14Days.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonNext14Days.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButtonNext14Days.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButtonNext14Days.setPreferredSize(new java.awt.Dimension(75, 20));

        jButtonNext7Days.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/ArrowRight.png"))); // NOI18N
        jButtonNext7Days.setText("Next 7 days");
        jButtonNext7Days.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonNext7Days.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButtonNext7Days.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButtonNext7Days.setPreferredSize(new java.awt.Dimension(75, 20));

        jButtonFacilities.setText("Facilities");
        jButtonFacilities.setPreferredSize(new java.awt.Dimension(120, 35));
        jButtonFacilities.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonFacilitiesActionPerformed(evt);
            }
        });

        jButtonSetupOverview.setText("Setup Overview");
        jButtonSetupOverview.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonSetupOverviewActionPerformed(evt);
            }
        });

        jButtonResetOveriew.setText("Normal View");
        jButtonResetOveriew.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonResetOveriewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelOverviewLayout = new javax.swing.GroupLayout(jPanelOverview);
        jPanelOverview.setLayout(jPanelOverviewLayout);
        jPanelOverviewLayout.setHorizontalGroup(
            jPanelOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOverviewLayout.createSequentialGroup()
                .addGroup(jPanelOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelOverviewLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanelOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonRoomArrowDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonRoomArrowUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(overviewCells1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelOverviewLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(jPanelOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelOverviewLayout.createSequentialGroup()
                                .addGroup(jPanelOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonSetupOverview, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(jButtonResetOveriew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                                .addComponent(jButtonBooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jButtonEditBooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jButtonSearchRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jButtonSearchCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jButtonFacilities, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelOverviewLayout.createSequentialGroup()
                                .addComponent(jButtonPrevious14Days, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonPrevious7Days, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonNext7Days, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonNext14Days, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(10, 10, 10))
        );
        jPanelOverviewLayout.setVerticalGroup(
            jPanelOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOverviewLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanelOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonBooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditBooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonSearchRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonFacilities, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonSearchCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelOverviewLayout.createSequentialGroup()
                        .addComponent(jButtonSetupOverview)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonResetOveriew)))
                .addGap(23, 23, 23)
                .addGroup(jPanelOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPrevious14Days, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPrevious7Days, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNext14Days, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNext7Days, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelOverviewLayout.createSequentialGroup()
                        .addComponent(jButtonRoomArrowUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(428, 428, 428)
                        .addComponent(jButtonRoomArrowDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(overviewCells1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanelOverview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanelOverview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBookingActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonBookingActionPerformed
    {//GEN-HEADEREND:event_jButtonBookingActionPerformed
        //Open booking-jDialog-window to perform a booking.
        jDialogBooking.setVisible(true);
        //This button could be implemented somehow with the Find/Search-button.
    }//GEN-LAST:event_jButtonBookingActionPerformed

    private void jButtonSearchCustomerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonSearchCustomerActionPerformed
    {//GEN-HEADEREND:event_jButtonSearchCustomerActionPerformed
        //Find/Search for different data in database.
        //     jDialogSearchCustomer.setVisible(true);
        //Data to be searched for, could be: RoomID, Customer-names, Dates, Availabilities/booked/reserved, BookingID, etc.
        jDialogSearchCustomer.setVisible(true);
    }//GEN-LAST:event_jButtonSearchCustomerActionPerformed

    private void jButtonEditBookingActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonEditBookingActionPerformed
    {//GEN-HEADEREND:event_jButtonEditBookingActionPerformed
        //Change data like start/end dates, names or roomsize in an existing booking/reservation.
    }//GEN-LAST:event_jButtonEditBookingActionPerformed

    private void jButtonSearchRoomActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonSearchRoomActionPerformed
    {//GEN-HEADEREND:event_jButtonSearchRoomActionPerformed
        //I dont know what the hell this button is for yet, but Im sure we will come up with something 1-2 days before the hand-in...
        jDialogSearchRoom.setVisible(true);
    }//GEN-LAST:event_jButtonSearchRoomActionPerformed

    private void jButtonRoomArrowUpActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonRoomArrowUpActionPerformed
    {//GEN-HEADEREND:event_jButtonRoomArrowUpActionPerformed
        //Show the 8 rooms below what is shown at Room1. If below 0 (zero) show RoomID's 001-008.
    }//GEN-LAST:event_jButtonRoomArrowUpActionPerformed

    private void jButtonRoomArrowDownActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonRoomArrowDownActionPerformed
    {//GEN-HEADEREND:event_jButtonRoomArrowDownActionPerformed
        //Show the next 8 rooms higher than what is shown at Room8. If higher than maximum room (RoomID 104) then show RoomID's 097-104.
    }//GEN-LAST:event_jButtonRoomArrowDownActionPerformed

    private void jButtonFacilitiesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonFacilitiesActionPerformed
    {//GEN-HEADEREND:event_jButtonFacilitiesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFacilitiesActionPerformed

    private void jButtonSetupOverviewActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonSetupOverviewActionPerformed
    {//GEN-HEADEREND:event_jButtonSetupOverviewActionPerformed
        ovc.setupjDialogSetupOverview(Room1, Room2, Room3, Room4, Room5, Room6, Room7, Room8, null);
    }//GEN-LAST:event_jButtonSetupOverviewActionPerformed

    private void jButtonResetOveriewActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonResetOveriewActionPerformed
    {//GEN-HEADEREND:event_jButtonResetOveriewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonResetOveriewActionPerformed

    private void jButtonSearchCustomerDetailsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonSearchCustomerDetailsActionPerformed
    {//GEN-HEADEREND:event_jButtonSearchCustomerDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSearchCustomerDetailsActionPerformed

    private void jComboBoxSearchRoomTypeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jComboBoxSearchRoomTypeActionPerformed
    {//GEN-HEADEREND:event_jComboBoxSearchRoomTypeActionPerformed
        int SearchRoomType = jComboBoxSearchRoomType.getSelectedIndex();
        switch (SearchRoomType)
        {
            case 0:
            jLabelSearchRoomTypePersonsNotifier.setText("");
            break;
            case 1:
            jLabelSearchRoomTypePersonsNotifier.setText("(1 person)");
            break;
            case 2:
            jLabelSearchRoomTypePersonsNotifier.setText("(2 persons)");
            break;
            case 3:
            jLabelSearchRoomTypePersonsNotifier.setText("(5 persons)");
            break;
        }
    }//GEN-LAST:event_jComboBoxSearchRoomTypeActionPerformed

    private void jButtonRoomSearchActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonRoomSearchActionPerformed
    {//GEN-HEADEREND:event_jButtonRoomSearchActionPerformed
        //Perform search of rooms from the entered details...
    }//GEN-LAST:event_jButtonRoomSearchActionPerformed

    private void jComboBoxBookingStartMonthActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jComboBoxBookingStartMonthActionPerformed
    {//GEN-HEADEREND:event_jComboBoxBookingStartMonthActionPerformed
        int year = (jComboBoxBookingStartYear.getSelectedIndex()+currentYear);
        int month = jComboBoxBookingStartMonth.getSelectedIndex();
        int dim = getDaysInMonth(month, year);
        switch (dim)
        {
            case 28:
                jComboBoxBookingEndDate = new JComboBox(list28days);
                break;
            case 29:
                jComboBoxBookingEndDate = new JComboBox(list29days);
                break;
            case 30:
                jComboBoxBookingEndDate = new JComboBox(list30days);
                break;
            default:
                jComboBoxBookingEndDate = new JComboBox(list31days);
                break;
        }
    }//GEN-LAST:event_jComboBoxBookingStartMonthActionPerformed

    private void jComboBoxBookingStartYearActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jComboBoxBookingStartYearActionPerformed
    {//GEN-HEADEREND:event_jComboBoxBookingStartYearActionPerformed
        int year = (jComboBoxBookingStartYear.getSelectedIndex()+currentYear);
        int month = jComboBoxBookingStartMonth.getSelectedIndex();
        int dim = getDaysInMonth(month, year);
        switch (dim)
        {
            case 28:
                jComboBoxBookingEndDate = new JComboBox(list28days);
                break;
            case 29:
                jComboBoxBookingEndDate = new JComboBox(list29days);
                break;
            case 30:
                jComboBoxBookingEndDate = new JComboBox(list30days);
                break;
            default:
                jComboBoxBookingEndDate = new JComboBox(list31days);
                break;
        }
    }//GEN-LAST:event_jComboBoxBookingStartYearActionPerformed

    private void jComboBoxBookingEndMonthActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jComboBoxBookingEndMonthActionPerformed
    {//GEN-HEADEREND:event_jComboBoxBookingEndMonthActionPerformed
        int year = (jComboBoxBookingEndYear.getSelectedIndex()+currentYear);
        int month = jComboBoxBookingEndMonth.getSelectedIndex();
        int dim = getDaysInMonth(month, year);
        switch (dim)
        {
            case 28:
                jComboBoxBookingEndDate = new JComboBox(list28days);
                break;
            case 29:
                jComboBoxBookingEndDate = new JComboBox(list29days);
                break;
            case 30:
                jComboBoxBookingEndDate = new JComboBox(list30days);
                break;
            default:
                jComboBoxBookingEndDate = new JComboBox(list31days);
                break;
        }
    }//GEN-LAST:event_jComboBoxBookingEndMonthActionPerformed

    private void jComboBoxBookingEndYearActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jComboBoxBookingEndYearActionPerformed
    {//GEN-HEADEREND:event_jComboBoxBookingEndYearActionPerformed
        int year = (jComboBoxBookingEndYear.getSelectedIndex()+currentYear);
        int month = jComboBoxBookingEndMonth.getSelectedIndex();
        int dim = getDaysInMonth(month, year);
        switch (dim)
        {
            case 28:
                jComboBoxBookingEndDate = new JComboBox(list28days);
                break;
            case 29:
                jComboBoxBookingEndDate = new JComboBox(list29days);
                break;
            case 30:
                jComboBoxBookingEndDate = new JComboBox(list30days);
                break;
            default:
                jComboBoxBookingEndDate = new JComboBox(list31days);
                break;
        }
        
    }//GEN-LAST:event_jComboBoxBookingEndYearActionPerformed

    private void jButtonBookingBookActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonBookingBookActionPerformed
    {//GEN-HEADEREND:event_jButtonBookingBookActionPerformed
        resetDialogBooking();
        //First, check if selected room is available in specified period
        //If selected room is available then perform booking of room
        String dateFrom = ((jComboBoxBookingStartDate.getSelectedIndex()-1)+"-"+(jComboBoxBookingStartMonth.getSelectedIndex()-1)+"-"+(String) jComboBoxBookingStartYear.getSelectedItem());
        String dateTo = (jComboBoxBookingEndDate.getSelectedIndex()+"-"+jComboBoxBookingEndMonth.getSelectedIndex()+"-"+(String) jComboBoxBookingEndYear.getSelectedItem());
        jdcbinsert.JDBCInsertRoom(jTextFieldBookingGuestID.getText(), jTextFieldBookingRoomNumber.getText(), "EmployeeID", dateFrom, dateTo, "BookingPrice", jTextFieldBookingFirstName.getText(), jTextFieldBookingLastName.getText(), jTextFieldBookingCountry.getText(), jTextFieldBookingPhoneNumber.getText(), jTextFieldBookingEmail.getText());
        jLabelBookingUnavailableNotifier.setText("Room has been booked...");
    }//GEN-LAST:event_jButtonBookingBookActionPerformed

    private int getDaysInMonth(int month, int year)
    {
        //Search Calender for how many days the specified month/year contains, and return the right list.
        cal.set(year, month, 1);
        int daysInMonth = cal.getActualMaximum(Calendar.DAY_OF_MONTH);
        return daysInMonth;
    }
    
    private void resetDialogBooking()
    {
        jTextFieldBookingFirstName.setText("");
        jTextFieldBookingLastName.setText("");
        jTextFieldBookingCountry.setText("");
        jTextFieldBookingPhoneNumber.setText("");
        jTextFieldBookingPhoneNumber.setText("");
        jTextFieldBookingEmail.setText("");
        jTextFieldBookingGuestID.setText("");
        jTextFieldBookingRoomNumber.setText("");
        jComboBoxBookingStartMonth.setSelectedIndex(0);
        jComboBoxBookingEndMonth.setSelectedIndex(0);
        jComboBoxBookingStartDate.setSelectedIndex(0);
        jComboBoxBookingEndDate.setSelectedIndex(0);
        jComboBoxBookingStartYear.setSelectedIndex(0);
        jComboBoxBookingEndYear.setSelectedIndex(0);
    }
    
    public void resetDialogDetails()
    {
        
    }
    
    public void resetDialogSearchRoom()
    {
        
    }
    
    public void resetDialogSearchCustomer()
    {
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Windows".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(CasablancaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(CasablancaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(CasablancaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(CasablancaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new CasablancaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupSearchRoomChoice;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonBooking;
    private javax.swing.JButton jButtonBookingBook;
    private javax.swing.JButton jButtonEditBooking;
    private javax.swing.JButton jButtonEditSelectedCustomerDetails;
    private javax.swing.JButton jButtonFacilities;
    private javax.swing.JButton jButtonNext14Days;
    private javax.swing.JButton jButtonNext7Days;
    private javax.swing.JButton jButtonPrevious14Days;
    private javax.swing.JButton jButtonPrevious7Days;
    private javax.swing.JButton jButtonResetOveriew;
    private javax.swing.JButton jButtonRoomArrowDown;
    private javax.swing.JButton jButtonRoomArrowUp;
    private javax.swing.JButton jButtonRoomSearch;
    private javax.swing.JButton jButtonSearchCustomer;
    private javax.swing.JButton jButtonSearchCustomerDetails;
    private javax.swing.JButton jButtonSearchRoom;
    private javax.swing.JButton jButtonSetupOverview;
    private javax.swing.JButton jButtonShowSelectedCustomerDetails;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBoxBookingEndDate;
    private javax.swing.JComboBox jComboBoxBookingEndMonth;
    private javax.swing.JComboBox jComboBoxBookingEndYear;
    private javax.swing.JComboBox jComboBoxBookingStartDate;
    private javax.swing.JComboBox jComboBoxBookingStartMonth;
    private javax.swing.JComboBox jComboBoxBookingStartYear;
    private javax.swing.JComboBox jComboBoxSearchEndDate;
    private javax.swing.JComboBox jComboBoxSearchEndMonth;
    private javax.swing.JComboBox jComboBoxSearchEndYear;
    private javax.swing.JComboBox jComboBoxSearchRoomType;
    private javax.swing.JComboBox jComboBoxSearchStartDate;
    private javax.swing.JComboBox jComboBoxSearchStartMonth;
    private javax.swing.JComboBox jComboBoxSearchStartYear;
    private javax.swing.JDialog jDialogBooking;
    private javax.swing.JDialog jDialogSearchCustomer;
    private javax.swing.JDialog jDialogSearchRoom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBookingNoChange1;
    private javax.swing.JLabel jLabelBookingNoChange10;
    private javax.swing.JLabel jLabelBookingNoChange2;
    private javax.swing.JLabel jLabelBookingNoChange3;
    private javax.swing.JLabel jLabelBookingNoChange4;
    private javax.swing.JLabel jLabelBookingNoChange5;
    private javax.swing.JLabel jLabelBookingNoChange6;
    private javax.swing.JLabel jLabelBookingNoChange8;
    private javax.swing.JLabel jLabelBookingNoChange9;
    private javax.swing.JLabel jLabelBookingUnavailableNotifier;
    private javax.swing.JLabel jLabelSearchCustomerBookingID;
    private javax.swing.JLabel jLabelSearchCustomerEmail;
    private javax.swing.JLabel jLabelSearchCustomerFirstName;
    private javax.swing.JLabel jLabelSearchCustomerGuestID;
    private javax.swing.JLabel jLabelSearchCustomerLastName;
    private javax.swing.JLabel jLabelSearchCustomerNationality;
    private javax.swing.JLabel jLabelSearchCustomerNoChange1;
    private javax.swing.JLabel jLabelSearchCustomerNoChange10;
    private javax.swing.JLabel jLabelSearchCustomerNoChange11;
    private javax.swing.JLabel jLabelSearchCustomerNoChange12;
    private javax.swing.JLabel jLabelSearchCustomerNoChange13;
    private javax.swing.JLabel jLabelSearchCustomerNoChange14;
    private javax.swing.JLabel jLabelSearchCustomerNoChange2;
    private javax.swing.JLabel jLabelSearchCustomerNoChange3;
    private javax.swing.JLabel jLabelSearchCustomerNoChange4;
    private javax.swing.JLabel jLabelSearchCustomerNoChange5;
    private javax.swing.JLabel jLabelSearchCustomerNoChange6;
    private javax.swing.JLabel jLabelSearchCustomerNoChange7;
    private javax.swing.JLabel jLabelSearchCustomerNoChange8;
    private javax.swing.JLabel jLabelSearchCustomerNoChange9;
    private javax.swing.JLabel jLabelSearchCustomerPhone;
    private javax.swing.JLabel jLabelSearchNoChange2;
    private javax.swing.JLabel jLabelSearchNoChange4;
    private javax.swing.JLabel jLabelSearchRoomNoChange1;
    private javax.swing.JLabel jLabelSearchRoomResultNotifier;
    private javax.swing.JLabel jLabelSearchRoomTypePersonsNotifier;
    private javax.swing.JList jList1;
    private javax.swing.JList jListSearchCustomerResult;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanelOverview;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButtonSearchRoomAvailable;
    private javax.swing.JRadioButton jRadioButtonSearchRoomCheckInOut;
    private javax.swing.JRadioButton jRadioButtonSearchRoomOccupied;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldBookingCountry;
    private javax.swing.JTextField jTextFieldBookingEmail;
    private javax.swing.JTextField jTextFieldBookingFirstName;
    private javax.swing.JTextField jTextFieldBookingGuestID;
    private javax.swing.JTextField jTextFieldBookingLastName;
    private javax.swing.JTextField jTextFieldBookingPhoneNumber;
    private javax.swing.JTextField jTextFieldBookingRoomNumber;
    private javax.swing.JTextField jTextFieldSearchCustomerBookingID;
    private javax.swing.JTextField jTextFieldSearchCustomerCountry;
    private javax.swing.JTextField jTextFieldSearchCustomerEmail;
    private javax.swing.JTextField jTextFieldSearchCustomerFirstName;
    private javax.swing.JTextField jTextFieldSearchCustomerGuestID;
    private javax.swing.JTextField jTextFieldSearchCustomerLastName;
    private javax.swing.JTextField jTextFieldSearchCustomerPhoneNumber;
    private spc.OverviewCells overviewCells1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent ae)
    {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
